### ISSUE TITLE
Filtering

### ISSUE THREAD

**Issue by rhysxevans** [ryck/MMM-TFL-Arrivals#2]
Hi

Would it be possible to add "line" filtering to the package ?  The API on the TFL website doesnt seem to be working as expected. (from https://blog.tfl.gov.uk/2015/12/07/unified-api-part-5-aot-arrivals-of-things/)

IE. https://api.tfl.gov.uk/StopPoint/naptanId/arrivals?mode=bus&line=XXX does not return only arrival times for bus XXX at naptanId

I have playeed around with your MMM-TFL-Arrivals.js file and have a very basic filter setup, under the
"processBuses: function(data)" section, to be as per below (added the first and last line below)

` if(bus.lineName === "XXX") {
  this.buses.data.push({
  stopName: bus.stationName,
  routeName: bus.lineName,
  direction: bus.destinationName,
  expectedDeparture: bus.expectedArrival,
  timeToStation: bus.timeToStation,
  modeName: bus.modeName
  });
  };
`

Obviously this should be done cleaner and better, but I dont know how to

Thoughts ?

Thansk

**Comment by rhysxevans** [comment]
apologies, it may also be worthwhile making the time until the bus is to arrive a parameter for the alerting ?

IE it may take me 10 mins to walk to the station so I would need to the bus to show up as "red" at lets say 12 mins ? (note this doesnt necessarily mena due

**Comment by imellor** [comment]
I changed it here:

>
 				if (minutes < 2) {
					timeToStation = "Due"
					if (this.config.color) {
						timeTabledCell.className += " due";
					}
				} else if (minutes < 11) {
					timeToStation = minutes + " " + "min";
					if (this.config.color) {
						timeTabledCell.className += " late";
					}
				} else {
					timeToStation = minutes + " " + "mins";

**Comment by ryck** [comment]
Added (lateThreshold) in 1.4.1
