### ISSUE TITLE
Stale data

### ISSUE THREAD

**Issue by imellor** [ryck/MMM-TFL-Arrivals#3]
I have tried this on 2 x different Magic Mirrors, so appears to be a bug than local configuration.
Bus stop 490014138S shows old cached data, however shows correct when data manual examined via CURL command.
Not sure why only this bus stop, but Northbound 490014138N works fine.

See example below: timestamp: "January 30, 2021 1:21 PM" Data shown is 2021-01-27

- [Object
data: Array(6)
0: {stopName: "Woodcote Green", routeName: "127", direction: "Purley", expectedDeparture: "2021-01-27T09:58:33Z", timeToStation: 116, …}
1: {stopName: "Woodcote Green", routeName: "463", direction: "Coulsdon South", expectedDeparture: "2021-01-27T10:01:12Z", timeToStation: 275, …}
2: {stopName: "Woodcote Green", routeName: "127", direction: "Purley", expectedDeparture: "2021-01-27T10:07:26Z", timeToStation: 649, …}
3: {stopName: "Woodcote Green", routeName: "S4", direction: "Roundshaw", expectedDeparture: "2021-01-27T10:17:42Z", timeToStation: 1265, …}
4: {stopName: "Woodcote Green", routeName: "127", direction: "Purley", expectedDeparture: "2021-01-27T10:18:07Z", timeToStation: 1290, …}
5: {stopName: "Woodcote Green", routeName: "463", direction: "Coulsdon South", expectedDeparture: "2021-01-27T10:18:28Z", timeToStation: 1311, …}
length: 6
__proto__: Array(0)
message: null
timestamp: "January 30, 2021 1:21 PM"
__proto__: Object]

**Comment by B1gG** [comment]
hey @imellor  did you solve the issue?

**Comment by imellor** [comment]
I left it and it fixed itself. Not sure if there is a cache somewhere?
